wandb:
  WANDB_API_KEY: 'XXXXXX'
  WANDB_USERNAME: 'XXXXXX'
  WANDB_PROJECT: 'XXXXXX'
train:
  img_size: 512
  batch_size: 32
  num_workers: 4
  hf_model: 'nvidia/mit-b0'
  p_loss: 2
  eps_loss: 0.000001
  ignore_index_loss: 255
  learning_rate: 0.00005
  weight_decay: 0.001
  epochs: 5
  warmup_epochs_factor: 0.125
  early_stopping: 2
  scheduler_mode: 'min'
  verbose_steps: 10
  filepath: 'output'
  mixed_precision: 'fp16'
  world_size: 1
  seed: 123